# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name : Create env file
        run : |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE }} >> .env
          echo TOKEN_SECRET=${{ secrets.SECRET_TOKEN }} >> .env
          ls -a
      - name: Build Docker image
        run : docker build . --file Dockerfile --tag ghcr.io/karnkm/backend222-app:latest
      - name : Push Docker image to registry
        run : |
          docker images
          docker push ghcr.io/karnkm/backend222-app:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login and Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker ps 
            docker rm -f be
            docker pull ghcr.io/karnkm/backend222-app:latest
            docker images
            docker-compose up -d
            docker ps -a
            docker image prune -f

